### ISSUE TITLE
'django.contrib.messages.middleware.MessageMiddleware' must be in MIDDLEWARE in orde r to use the admin application

### ISSUE THREAD

**Issue by Ajinkz** [ricleal/DjangoPlotLy#1]
ERRORS:
?: (admin.E408) 'django.contrib.auth.middleware.AuthenticationMiddleware' must be in MIDDLEWARE in o
rder to use the admin application.
?: (admin.E409) 'django.contrib.messages.middleware.MessageMiddleware' must be in MIDDLEWARE in orde
r to use the admin application.

**Comment by ricleal** [comment]
This was a Django 3 problem. Never had tested it before. It's solved now.
